### ISSUE TITLE
Show id or name when node is collapsed

### ISSUE THREAD

**Issue by dsbecker** [litejs/json-lite#2]
If a node has an id, name, or other useful property, it would be helpful to show that in the summary when the node is collapsed (and maybe even when expanded).  Something like this maybe:
```
{ ▶ id = MyClass, 7 properties, 75 KB }
```
That would make it much easier to collapse large files and still find what you're looking for.

Thanks!

**Comment by lauriro** [comment]
I like the idea but proper implementation is tricky.

Just adding this to summary is not ideal because this is not searchable with ctrl+F.
Adding extra regular dom nodes would break select-copy working json even when collapsed.

will think about it

**Comment by lauriro** [comment]
Current git version shows object first properties when collapsed,
it is up to backend to put most useful stuff to beginning of object.

I will think about it some other night again

**Comment by dsbecker** [comment]
FYI, here's how IntelliJ IDEA does it (and what inspired this request):
![image](https://cloud.githubusercontent.com/assets/14081970/22385705/a1ba0882-e488-11e6-89a4-1a480c2acc32.png)
