### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by thany** [litejs/json-lite#60]
With the browser in dark mode, this extension creates a light mode view, which is really too bright for any dark mode user.

Can you please make the JSON view show dark mode when the browser is in dark mode? Thanks.

I'm on Firefox 91.0.2, and `devtools.jsonview.enabled` is indeed set to `false`.

**Comment by lauriro** [comment]
There is "Theme" option with "firefox-dark" colors. Automatic switching may come in the future.
