### ISSUE TITLE
Tries to convert the page to Json on some backend activity

### ISSUE THREAD

**Issue by gjobin** [litejs/json-lite#66]
I have the tool enabled on my Chrome browser. The issue happened both on Windows and Mac.
Sometimes, when some backend get or post happens, the extensions tries to convert the web page to json, and fails. (Content is a normal website)

I've had it happen on Amazon while trying to complete an order, and also on Deluge, when trying to add a new torrent file.

As a work around, it would be great if we could provide a blacklist to disable activity on some sites/domains. 

Regards

**Comment by lauriro** [comment]
Not sure can this be an issue with this extension,
JSON Lite do not capture backend traffic, in injects a script into webpage and run once.

Could there be any other extension to blame?
Or could you set up an isolated example where this issue occurs?

**Comment by lauriro** [comment]
Not sure can this be an issue with this extension,
JSON Lite do not capture backend traffic, in injects a script to dom.

Could there be any other extension to blame?
Or could you set up an isolated example where this issue occurs?

**Comment by gjobin** [comment]
Disabling the extension resolved the issue. I will try to consistently reproduce and/or generate a video of the issue.

**Comment by gjobin** [comment]
Uploading a torrent file to deluge, it causes the issue consistently.
![image](https://github.com/lauriro/json-lite/assets/9118970/21433777-c882-42bb-a446-d3e9ab65a783)

Once I press Add:
![image](https://github.com/lauriro/json-lite/assets/9118970/f99a0de2-f3f8-4a7e-a1b7-20483622777e)

Once I disable json-lite, the issue is gone and it works as expected

**Comment by lauriro** [comment]
Could you try out version 24.4.0?
