### ISSUE TITLE
Jsonlite stopped working for updated chrome version 117.

### ISSUE THREAD

**Issue by jeetonweb** [litejs/json-lite#71]
Chrome Version: 117.0

It was well and fine until I updated the chrome. After the update, Jsonlite is not working, instead the Chrome default pretty print option comes for viewing any JSON output in browser.

**Comment by boghyon** [comment]
Star https://bugs.chromium.org/p/chromium/issues/detail?id=1485052.

For Edge users, it can be disabled with `edge://flags/#edge-json-viewer` (https://github.com/lauriro/json-lite/pull/67). So far, I couldn't find any equivalent setting for Chrome.

**Comment by cb-miguel** [comment]
Same!

**Comment by boghyon** [comment]
The breaking Chromium change is reverted for now but the "feature" might be introduced again. If at all, then:

> We certainly wouldn't want to break extensions with this change. (Source: https://bugs.chromium.org/p/chromium/issues/detail?id=1449151#c21)

This issue can be closed.
